# Basic plugin information. The 'name' field is what shows up when you run
# /plugins in game. 'main' is the fully-qualified class name that extends
# JavaPlugin. 'api-version' tells Spigot which set of API features we depend on.
name: NoBuild
main: com.example.nobuild.NoBuild
version: 1.0
api-version: 1.21

# This plugin does not define any permissions. Only server operators
# are allowed to place blocks. WorldGuard or similar plugins may still
# impose additional restrictions on a per-region basis.

# Additional ideas:
#   You could define more permissions in the future, for example
#   'nobuild.admin' to reload plugin configuration, or
#   'nobuild.tempbypass' for temporary building permissions.
